# Generated by Django 5.0.6 on 2024-05-21 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('sis_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('section_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('last_activity_at', models.DateTimeField()),
                ('total_activity_time', models.FloatField(blank=True, null=True)),
                ('sis_course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_user_id', models.CharField(max_length=100)),
                ('inactive_days', models.IntegerField(blank=True, null=True)),
                ('current_grade', models.FloatField(blank=True, null=True)),
                ('current_score', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('unposted_current_score', models.FloatField(blank=True, null=True)),
                ('unposted_current_grade', models.FloatField(blank=True, null=True)),
                ('unposted_final_score', models.FloatField(blank=True, null=True)),
                ('unposted_final_grade', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentlist', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
