# Generated by Django 5.0.6 on 2025-02-19 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('due_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sis_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('section_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('last_activity_at', models.DateTimeField()),
                ('total_activity_time', models.FloatField(blank=True, null=True)),
                ('sis_course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sis_user_id', models.CharField(max_length=100)),
                ('inactive_days', models.IntegerField(blank=True, null=True)),
                ('current_grade', models.FloatField(blank=True, null=True)),
                ('current_score', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('unposted_current_score', models.FloatField(blank=True, null=True)),
                ('unposted_current_grade', models.FloatField(blank=True, null=True)),
                ('unposted_final_score', models.FloatField(blank=True, null=True)),
                ('unposted_final_grade', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentlist')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missing', 'Missing'), ('floating', 'Floating')], db_index=True, max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.assignment')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentlist')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
