# Generated by Django 5.0.6 on 2025-04-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
