# Generated by Django 4.1 on 2024-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="section",
            field=models.CharField(default="default_section", max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(default="default_status", max_length=100),
        ),
    ]
