# Generated by Django 4.1 on 2024-06-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_assignment_section_assignment_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="assignment", name="section",),
    ]
