# Generated by Django 4.2.20 on 2025-04-03 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_enrollment_last_activity_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
