# Generated by Django 4.1 on 2024-06-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_assignment_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="student_id",
            field=models.CharField(default="default_student_id", max_length=100),
        ),
        migrations.AlterField(
            model_name="performance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="students.studentlist",
            ),
        ),
    ]
