# Generated by Django 4.1 on 2024-07-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_assignment_student_id_alter_performance_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="students.studentlist",
                to_field="student_id",
            ),
        ),
    ]
