# Generated by Django 4.1 on 2024-07-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_assignment_student_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Performance",),
    ]
